services:
  - type: web
    name: BrokerGPT
    region: oregon
    repo: https://github.com/BrokerGPT2025/BrokerGPT
    branch: main
    rootDir: web
    buildCommand: cd "$RENDER_PROJECT_DIR/web" && npm install && npm run build
    startCommand: cd "$RENDER_PROJECT_DIR/web" && npm start
    envVars:
      - key: PORT
        sync: false
      - key: NODE_ENV
        value: production