services:
  - type: web
    name: BrokerGPT
    region: oregon
    repo: https://github.com/BrokerGPT2025/BrokerGPT
    branch: main
    rootDir: web
    buildCommand: npm ci && npx vite build
    startCommand: npx serve -s dist --listen $PORT
    envVars:
      - key: PORT
        sync: false
      - key: NODE_ENV
        value: production