services:
  - type: web
    name: BrokerGPT
    region: oregon
    repo: https://github.com/BrokerGPT2025/BrokerGPT
    branch: main
    rootDir: web
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_PORT
        value: 10000
